### ISSUE TITLE
Error deleting a Workflow

### ISSUE THREAD

**Issue by sscaglia** [microsoft/farmvibes-ai#135] opened 2023-12-24 19:29 UTC
Hello:

I 'm able to cancel a workflow using run.cancel() and this works fine.

I also tried deleting a workflow using run.delete() but it returns an error "object has no attribute 'delete'". According to documentation, this can be used to delete a complete workflow. It's current status is 'cancelled'.

What could be the issue?

Thanks

**Comment by rafaspadilha** [comment] 2023-12-27 13:43
Hi, @sscaglia. Thank you for raising this issue.

Could you provide a code snippet or a reproducible example? 

The error _"object has no attribute 'delete'"_ might mean that you are trying to use the delete method of an object that is not a `VibeWorkflowRun`. Another possibility is to use the method `delete_run` from the client, passing a `run_id` as argument. Below you can see two examples:

```python
from vibe_core.client import get_default_vibe_client
client = get_default_vibe_client()

# for this example, we will get the last executed run
run_id = client.list_runs()[-1]

# deleting with the client
client.delete_run(run_id)

# or getting the run object and deleting it
run = client.get_run_by_id(run_id)
run.delete()

**Comment by sscaglia** [comment] 2023-12-28 21:37
Hello:

I deleted the notebook, but I was doing something like:

from vibe_core.client import get_default_vibe_client
client = get_default_vibe_client()

# get a list of runs
print(client.list_runs())

# delete the run that failed
run = client.get_run_by_id('run-id')
run.delete()

Again, run.cancel() worked fine.

**Comment by rafaspadilha** [comment] 2023-12-29 12:51
I couldn't replicate the error on my end. I tried:

- Getting a run (with `client.get_run_by_id('run-id')`), which had a **done** status, and deleting it. 
- Deleting a run with **cancelled** status.
- Cancelling a deleted run has no effect, as intended.

All of above worked fine on my end.

Please, let me know if you are able to reproduce that on your end and, if so, share a reproducible example so I can diagnose that.

**Comment by rafaspadilha** [comment] 2024-01-29 18:18
Closing this issue for now. @sscaglia please, feel free to reopen it if your problem persists.

**Closed by rafaspadilha** 2024-01-29 18:18 UTC
Labels: question
