### ISSUE TITLE
What-if scenario evaluation for carbon sequestration notebook

### ISSUE THREAD

**Issue by Click2cloud-Abhijeet** [microsoft/farmvibes-ai#151] opened 2024-02-19 12:02 UTC
Hi team ,
Hope you are doing good !!!

I was trying to run a **"whatif.ipynb"** notebook in new **Farmvibes-ai cluster** , but Notebook is getting failed.
When I checked using **run.reason** it is giving me below reason.

```
RuntimeError: 
Failed to run op whatif_comet_op in workflow run id a1225b9a-1e6b-4e9a-a8a3-e5d4b1a2bb12 for input with message id 00-a1225b9a1e6b4e9aa8a3e5d4b1a2bb12-fc18cd0aed4b24db-01. 

Error description: 
<class \'RuntimeError\'>:  PyngrokNgrokError("The ngrok process errored on start: {}.".format(ngrok_process.startup_error),
pyngrok.exception.PyngrokNgrokError: 

The ngrok process errored on start: Your ngrok-agent version "2.3.41" is too old. The minimum supported agent version for your account is "3.2.0". Please update to a newer version with `ngrok update`, by downloading from https://ngrok.com/download, or by updating your SDK version. Paid accounts are currently excluded from minimum agent version requirements. To begin handling traffic immediately without updating your agent, upgrade to a paid plan: https://dashboard.ngrok.com/billing/subscription.

ERR_NGROK_121.
```

I am also providing a Screen shot of an error.
Please help me to find the solution for it.
Thank you 
![whatif_error](https://github.com/microsoft/farmvibes-ai/assets/113983105/82d4498d-f8b2-46f4-8fca-1c6f45c2f79b)

**Comment by v-ngangarapu** [comment] 2024-02-19 20:57
Hi Abhijit,
 Thanks for reaching us with your observations. I was able to reproduce the same results you're seeing. 

Will do more research on our end and let you know the possible solutions.

Thanks

**Comment by v-ngangarapu** [comment] 2024-02-23 15:05
Hi
The issue is happening due to recent upgrade done to ngrok package. It's resolved now. 
Will be pushing the change in next build.

Thanks

**Comment by Click2cloud-Abhijeet** [comment] 2024-02-26 12:01
> Hi The issue is happening due to recent upgrade done to ngrok package. It's resolved now. Will be pushing the change in next build.
> 
> Thanks

Thank you for your response and happy to hear that.

**Comment by gmesserman** [comment] 2024-02-26 12:04
Hello, 

When do you expect this to be resolved?

Thanks,
GIl

**Comment by v-ngangarapu** [comment] 2024-02-28 20:28
Hi Gil,
 It should be pushed soon, I don't have the exact date.

Thanks

**Comment by kennrichie** [comment] 2024-03-22 04:50
> Hi Gil, It should be pushed soon, I don't have the exact date.
> 
> Thanks

Thanks for the information, but I got the same issue today, 22nd of March, weeks after

**Comment by imanema1** [comment] 2024-03-23 19:25
me too

**Comment by arewtech** [comment] 2024-03-31 19:45
Is this finished already? I also found the same thing as above 😭

**Comment by rafaspadilha** [comment] 2024-04-01 13:11
Hi, folks. We are planning a release for this week with a fix for this issue. Thank you for your patience.

**Comment by rafidhasan448** [comment] 2024-04-02 13:22
When will this issue be solved ?

**Comment by rafaspadilha** [comment] 2024-04-05 19:05
Folks, we just released a new version of FarmVibes.AI (PR #157) that fixes updates ngrok version and should fix this issue. 
Please, let us know if you are able to test it and if any more issue arises.

**Comment by rafaspadilha** [comment] 2024-04-15 13:42
Closing this for now. Please, let us know if you still have any issues.

**Closed by rafaspadilha** 2024-04-15 13:42 UTC
Labels: bug, workflows
