### ISSUE TITLE
Discrepancy in Units between Input Sensor Data and Heatmap Output for Humidity and Salinity Properties.

### ISSUE THREAD

**Issue by click2cloud-sagarB** [microsoft/farmvibes-ai#134] opened 2023-12-20 13:17 UTC
Dear Farmvibes Team,
I have created various nutrient heatmaps for different properties using the "heatmap_using_classification" Workflow, however when I created heatmaps for Humidity and Salinity properties, the output units of measurement (shown on the legend) do not match the input units as specified in sensor_samplesA.geojson
Example: The humidity measurement is in the range of 65.54 and the salinity value is in the range of 152, however when a heatmap is created for both, the legend shows output in the ranges of 0.0027 to 0.003 and 19 to 23, respectively.

Attached to this issue, you will find below given files:
farm_boundaryA.geojson
sensor_samplesA.geojson
Notebook sample I used

[files.zip](https://github.com/microsoft/farmvibes-ai/files/13727737/files.zip)

**Comment by v-ngangarapu** [comment] 2023-12-21 18:25
Hi Sagar,
 Thanks for reaching out with observations you having. I was able to download files uploaded and able to reproduce the same results. Will do more research on this and get back to you.

Thanks

**Comment by v-ngangarapu** [comment] 2023-12-21 20:43
Hi Sagar,
The issue has been identified and fixed. Will be receiving the fix for this in next release.

Thanks

**Comment by rafaspadilha** [comment] 2024-01-24 12:35
Hi, @click2cloud-sagarB. We just published a new release that should fix this issue.
Please, let us know if you still see this happening.
Thanks!

**Comment by click2cloud-sagarB** [comment] 2024-01-31 13:12
Hello, @rafaspadilha The workflow farm_ai/agriculture/heatmap_using_classification fails for the same files baramati_farm_boundaryA, baramati_sensor_samplesA that were provided above in "files.zip" after upgrading the cluster for the latest version. I'm providing the workflow log file for the unsuccessful build.

[heatmap logs.json](https://github.com/microsoft/farmvibes-ai/files/14112073/heatmap.logs.json)

**Comment by rafaspadilha** [comment] 2024-01-31 19:11
The `reason` field of the log shows that you are running an older version of the workflow. It shows some parameters that were removed in the fix from last release. Please, could you update your cluster and try again?

**Comment by v-ngangarapu** [comment] 2024-02-01 03:41
@click2cloud-sagarB - If you have already updated cluster verify your local notebook of heatmap.

We excluded the input parameter "distribute_output" since it's no longer required. These changes updated in notebook in latest release.

**Comment by rafaspadilha** [comment] 2024-02-05 12:47
Thanks for the reply, @click2cloud-sagarB. It was an issue with scaling the input values which was not taking into account the different ranges of input variables. I'm closing this issue for now, but feel free to reopen it if the problem happens again.

**Closed by rafaspadilha** 2024-02-05 12:47 UTC
Labels: bug, workflows
