### ISSUE TITLE
Error in Running the notebook 03_aml_training.ipynb

### ISSUE THREAD

**Issue by hnlf123** [microsoft/farmvibes-ai#38] opened 2023-02-13 10:53 UTC
Dear Farm Vibes - Team,

I successfully ran the notebooks _01_dataset_generation.ipynb_ and _02_visualize_dataset.ipynb_. But I am facing the error in running the _03_aml_training.ipynb_. Anyone could assist me in this regard.

**Error Log**:

```
Converting CDLMask CRS from EPSG:5070 to EPSG:32611
Converting CDLMask resolution from 30.0 to 10.0
Traceback (most recent call last):
  File "03_aml_training.py", line 210, in <module>
    save_chips_locally(data.train_dataloader(), os.path.join(AML_DATASET_DIR, "train"))
  File "/home/azureuser/farmvibes-ai/notebooks/crop_segmentation/notebook_lib/modules.py", line 31, in save_chips_locally
    batch = next(iter(dataloader))
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchgeo/datasets/geo.py", line 876, in __getitem__
    samples = [ds[query] for ds in self.datasets]
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchgeo/datasets/geo.py", line 876, in <listcomp>
    samples = [ds[query] for ds in self.datasets]
  File "/home/azureuser/farmvibes-ai/notebooks/crop_segmentation/notebook_lib/datasets.py", line 293, in __getitem__
    sample = super().__getitem__(query)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchgeo/datasets/geo.py", line 427, in __getitem__
    data = self._merge_files(filepaths, query, self.band_indexes)
AttributeError: 'CDLMask' object has no attribute 'band_indexes'
```

**Comment by rafaspadilha** [comment] 2023-02-14 12:34
Hi, @hnlf123. Thank you for using FarmVibes.AI. 
I couldn't reproduce the error with the notebook and environment provided in the repo. 

The error is coming from `torchgeo`, so I imagine you are running the notebook with a different version than the one specified by the conda environment (`torchgeo==0.3.0`). 

Please, could you verify if you have created the `crop_seg` environment and have activated it? 

```
$ conda env create -f ./crop_env.yaml
$ conda activate crop-seg
```

**Comment by rafaspadilha** [comment] 2023-02-24 14:58
Hi, @hnlf123, were you able to verify the version of `torchgeo`? Does the error still persist?

**Comment by rafaspadilha** [comment] 2023-03-14 12:14
Closing this for now. Please, let us know if the error still persists.

**Closed by rafaspadilha** 2023-03-14 12:14 UTC
Labels: bug
