### ISSUE TITLE
Getting an Error with Weed Detection Notebook

### ISSUE THREAD

**Issue by Click2cloud-Abhijeet** [microsoft/farmvibes-ai#102] opened 2023-05-26 12:32 UTC
Hello Team, 
I would like to know that , I was trying to run '**Weed Detection**" notebook . I have provided the given required parameters like **URL** and **.shp file** .
But while running the Notebook , I am getting an error .

![Capture](https://github.com/microsoft/farmvibes-ai/assets/113983105/4ea41e40-d942-4a99-973a-86860d9e85a3)

Input Parameters I am sharing is -  URL of till Image, .shpe file , Date Range  = datetime.now().

I am also sharing the error log which I got .

> RuntimeError: Failed to run op weed_detection in workflow run id df63dfe4-8f74-46af-9c24-62c839d1ed8a for input with message id 00-df63dfe48f7446af9c2462c839d1ed8a-a6f37119c660ebd9-01. 
> Error description: <class 'RuntimeError'>: Traceback (most recent call last):
> 
> File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 133, in run_op
> return factory.build(spec).run(input, cache_info)
>
> File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 106, in run
>     stac_results = self._call_validate_op(**items)
>
> File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 72, in _call_validate_op
>     results = self.callback(**kwargs)
>
> File "/app/ops/weed_detection/weed_detection.py", line 158, in detect_weeds
>     model = train_model(
>
> File "/app/ops/weed_detection/weed_detection.py", line 29, in train_model
>     ar, _ = mask(
>
> File "/opt/conda/lib/python3.8/site-packages/rasterio/mask.py", line 178, in mask
>     shape_mask, transform, window = raster_geometry_mask(
>
> File "/opt/conda/lib/python3.8/site-packages/rasterio/mask.py", line 80, in raster_geometry_mask
>     window = geometry_window(dataset, shapes, pad_x=pad_x, pad_y=pad_y)
>
> File "/opt/conda/lib/python3.8/site-packages/rasterio/features.py", line 447, in geometry_window
>     all_bounds = [bounds(shape) for shape in shapes]
>
> File "/opt/conda/lib/python3.8/site-packages/rasterio/features.py", line 447, in <listcomp>
>     all_bounds = [bounds(shape) for shape in shapes]
>
> File "/opt/conda/lib/python3.8/site-packages/rasterio/features.py", line 390, in bounds
>     return _bounds(geom, north_up=north_up, transform=transform)
>
> File "rasterio/_features.pyx", line 440, in rasterio._features._bounds
> IndexError: tuple index out of range.

I am request you to kindly look into this issue & provide possible solution , it will going to help me .

Thanks & Regards
Abhijit

**Comment by robertomest** [comment] 2023-06-06 14:21
Hello @Click2cloud-Abhijeet. The error indicates something is going wrong in the `rasterio` library when masking the input image with the input geometry, but the cause of the problem is not clear to me. Could you share the inputs to the workflow so we can try to reproduce the problem?

**Comment by Click2cloud-Abhijeet** [comment] 2023-06-07 04:56
Hi @robertomest , thanks for your reply.
As per your suggestion I am sending the Inputs which I am using in this notebook.
I am sharing tiff Image file , and shape files . **Note** - Both files are in .zip file, Please extract it before use.
[input_files.zip](https://github.com/microsoft/farmvibes-ai/files/11672613/input_files.zip)

Thanks & Regards
Abhijeet

**Comment by zaned897** [comment] 2023-06-18 20:17
Hi @Click2cloud-Abhijeet  as  @robertomest mentioned, the issue appears to be that the input geometry and the image do not correspond. I have resolved the problem using the following approach:

-     Reduce the area of the shapefile (shp).

-     Increase the offset in the parameters.

**Comment by robertomest** [comment] 2023-06-19 19:55
Hello @Click2cloud-Abhijeet. Sorry for the delay. I've investigated and it seems we have two problems:
1. The input geometry is a set of points, instead of a polygon. The script assumes the shapefile contains a single polygon with the field bounds, so we are selecting a single point. You can fix this by, for example, taking the convex hull of the points in the shapefile, or any other way you prefer:
```python
# Change this line in the notebok
# geometry = shpg.mapping(data_frame.geometry.iloc[0])
# to something like this
geometry = shpg.mapping(data_frame.unary_union.convex_hull)
# Or use a different shapefile in the expected format
```
2. The input image seems to be a single-band raster. The current workflow expects an RGBA image from a drone. I will work with the team to try to improve the workflow so it is more flexible in relation to the input raster and update here. Please note that the quality of the results may vary depending on the bands used.

**Comment by Click2cloud-Abhijeet** [comment] 2023-06-20 04:29
@robertomest , thank you for your reply . 
Let me try this , and I will let you know what I am getting after adding this .

**Comment by rafaspadilha** [comment] 2023-09-18 17:19
@Click2cloud-Abhijeet, were you able to test the new version of the workflow? We've updated it to operate on rasters with an arbitraty number of bands.

**Comment by Click2cloud-Abhijeet** [comment] 2023-09-19 05:21
Hi all,
 Thank you for your update regarding New version of workflow.

Let me test the new version & I will give you my response.

Thanks & Regards
Abhijit Meshram
________________________________

**Comment by rafaspadilha** [comment] 2023-10-20 12:40
Closing this issue for now, @Click2cloud-Abhijeet. Let us know if you still have any doubts or bump into any issues with the workflow.

**Closed by rafaspadilha** 2023-10-20 12:40 UTC
Labels: notebooks, workflows

**Comment by Click2cloud-Abhijeet** [comment] 2023-10-20 12:44
Sure @rafaspadilha , you can close this . Thanks for the support.
