### ISSUE TITLE
SpaceEye & NDVI Timelapse workflow creates rasters and lapses for future dates

### ISSUE THREAD

**Issue by richstep** [microsoft/farmvibes-ai#87] opened 2023-04-13 22:42 UTC
My time range is from March 13 to April 12 (today is April 13), yet I get output for April 15th and 20th, 2023.

`time_range = (datetime(2023, 3, 13), datetime(2023, 4, 12))`

![future-dates](https://user-images.githubusercontent.com/733563/231898204-5a7f9409-91d0-4676-bceb-6f5a1d871a29.png)

This this export of the jupyter notebook:
https://github.com/microsoft/farmvibes-ai/files/11227038/timelapse_visualization-Thomas40.pdf

**Comment by rafaspadilha** [comment] 2023-04-14 19:18
Hi, @richstep. [Great Scott! Seems like your FarmVibes instance is hitting 88 mph](https://media.giphy.com/media/ZhESFK96NxbuO1yDgy/giphy.gif). 

Jokes aside, thanks for raising this.

SpaceEye works with a window of 48 days by default (the parameter `duration` of the SpaceEye workflow, whose documentation can be seen by running `client.document_workflow("data_ingestion/spaceeye/spaceeye_interpolation")`). 

If your time range is smaller than that, we add a padding to fill the whole temporal window. In your scenario, your time range has 33 days (March 13th to April 14th), so the difference (15 days) is added as padding. SpaceEye will generate a cloud-free image for each day of the window (with a damped interpolation approach, in the particular case of the [workflow used in the timelapse notebook](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/sentinel/spaceeye_ndvi.yaml)). 

That is why you are seeing rasters outside your input time range. If you check the number of SpaceEye or NDVI outputs, there will be 48 of them. You will also see a number of rasters that are before your time range, which were not downloaded, but were instead generated by SpaceEye.


A few possibilities to consider:

1. Ignore the rasters outside your input time range.  

2. Increase the time range to consider days before March 13th. Adding more days to fill the whole window will potentially improve the overall quality of the output rasters, as more data will be available for SpaceEye.

3. Decrease the `duration` value when running the workflow. This, in turn, means SpaceEye will have less available input data to generate the pixels originally occluded by clouds, which may decrease the quality of the results. This can be done directly altering the [yaml file of the custom workflow](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/sentinel/spaceeye_ndvi.yaml), for example, if you want to change `duration` to 30 days:

```
name: spaceeye_ndvi
sources:
  user_input:
    - spaceeye.user_input
sinks:
  ndvi: ndvi.index_raster
  spaceeye_raster: spaceeye.raster
parameters:
  pc_key:
tasks:
  spaceeye:
    workflow: data_ingestion/spaceeye/spaceeye_interpolation
    parameters:
      pc_key: "@from(pc_key)"
      duration: 30
  ndvi:
    workflow: data_processing/index/index
    parameters:
      index: ndvi
edges:
  - origin: spaceeye.raster
    destination:
      - ndvi.raster
```

**Comment by richstep** [comment] 2023-04-17 20:05
Hi @rafaspadilha, LOL and thanks for the detailed response! That makes a lot of sense. I ran it for 48 days and I got what you described. That leads me to another question, why didn't the clouds get removed for March 22 and April 1, 2023? Is this expected behavior sometimes?

```
# Define our workflow inputs.
geom = shpg.Point(-120.090833,36.574722).buffer(.01, cap_style=3)
time_range = (datetime(2023, 2, 27), datetime(2023, 4, 16))
```
![3-23-2023_with clouds](https://user-images.githubusercontent.com/733563/232597655-881594cc-0a07-4090-b2f7-5e4b774591e5.png)

https://user-images.githubusercontent.com/733563/232597703-895b08e4-6748-4f22-952f-55489944d671.mp4

**Comment by robertomest** [comment] 2023-04-17 22:08
Hi @richstep. Remaining clouds in the output are usually caused by a failure in the cloud detection step. We rely on cloud masks generated by separate machine learning models and, while they perform pretty well, they will occasionally miss some clouds. If a region is not marked as cloudy, we won't inpaint it, and the clouds will also be present in the output. If you are curious, you can check the cloud masks by running the `data_ingestion/sentinel2/preprocess_s2_improved_masks` workflow using the same inputs (this should run really fast because all the outputs will be fetched from the cache). More information is also available at the [Sentinel/SpaceEye notebook](https://github.com/microsoft/farmvibes-ai/tree/main/notebooks/sentinel/sentinel_spaceeye.ipynb).

**Comment by rafaspadilha** [comment] 2023-05-18 20:14
Closing this issue for now. @richstep, feel free to reopen if you have more questions.

**Closed by rafaspadilha** 2023-05-18 20:14 UTC
