### ISSUE TITLE
Failure to generate SpaceEye and NDVI Timelapse of the farm for year 2022.

### ISSUE THREAD

**Issue by click2cloud-sagarB** [microsoft/farmvibes-ai#51] opened 2023-02-23 12:40 UTC
Dear Farmvibes Team,
While running "timelapse_visualization.ipynb" notebook the task "spaceeye.preprocess.s2.list"
did not succeed and encountered an error **"Could not find orbit element when parsing manifest XML for item S2A_MSIL2A_20221210T053221_R105_T43QDA_20221210T222819"**

I have attached the screenshot of task which was failed along with its log for better understanding.
I have also attached the text file containing polygonal co-ordinates of farm for which workflow execution fails.

![2022 (1)](https://user-images.githubusercontent.com/115791095/220905486-efe0e679-f58c-4848-b40d-e162fd41ebe7.jpg)

![2022](https://user-images.githubusercontent.com/115791095/220905532-e8d588db-a562-4235-b9ba-93788fe8d305.jpg)

[Farm Co-ordinates.txt](https://github.com/microsoft/farmvibes-ai/files/10813527/Farm.Co-ordinates.txt)

**Comment by rafaspadilha** [comment] 2023-02-23 21:17
Hey, @click2cloud-sagarB. Thank you for providing the polygon of the region you are running. 

I executed the workflow in my VM, but I can't reproduce the error that you are seeing. 

I was able to run in my machine with the whole 2022 year, and the workflow executed past the spaceeye.preprocess.s2.list operation. I also manually fetched the item with the Planetary Computer API and tried retrieving the orbit element (by running the part of the code that raises the error that you are seeing) and it ran successfully. 

I believe that something went wrong when reaching the Planetary Computer API and the workflow run couldn't get the proper response with the orbit element required. We retry this request a few times if it fails the first try, so it must have been something consistent.  

I will improve the error message and add a test to check for bad/incomplete responses from the Planetary Computer API. 

Please, could you try running the workflow again and letting me know if the error repeats?

**Comment by click2cloud-sagarB** [comment] 2023-02-24 09:25
Hi @rafaspadilha,
Thank you for your feedback.
I run the workflow again for the year 2022 for first time it was failed again but now when I try it for 2nd time it is running successfully.

**Comment by rafaspadilha** [comment] 2023-02-24 11:42
Thanks, @click2cloud-sagarB. Closing this issue for now. Please, let us know if you face this while running other workflows.

**Closed by rafaspadilha** 2023-02-24 11:42 UTC
